function filtered = preprocessEEG(signal, fs)
    % Bandpass filter (0.5–30 Hz)
    d = designfilt('bandpassiir', ...
        'FilterOrder', 4, ...
        'HalfPowerFrequency1', 0.5, ...
        'HalfPowerFrequency2', 30, ...
        'SampleRate', fs);
    filtered = filtfilt(d, signal);
end
